### ISSUE TITLE
Some points I found while reviewing

### ISSUE THREAD

**Issue by itzmeanjan** [smartcontractkit/link-token-sidechain-evm#1]
- I don't think [this](https://github.com/smartcontractkit/link-token-maticnetwork/blob/f17da49b40b6d71d89b0078bfe906b771922d7aa/flat/LinkTokenOnMatic.sol#L666) check is required, because we're just extracting transaction sender address using `ContextMixin.msgSender()`, which getting passed in [_burn()](https://github.com/smartcontractkit/link-token-maticnetwork/blob/f17da49b40b6d71d89b0078bfe906b771922d7aa/flat/LinkTokenOnMatic.sol#L1700).
- You can also make [it](https://github.com/smartcontractkit/link-token-maticnetwork/blob/f17da49b40b6d71d89b0078bfe906b771922d7aa/flat/LinkTokenOnMatic.sol#L1661) `_msgSender()`.
- Your work also adds support for meta transactions, this is really good, but all these functions need not to be implemented for successfully enabling assets transfer in between Ethereum & Matic Network. Rather you just need to implement 
    - `deposit`
    - `withdraw`

You can check [this](https://gist.github.com/itzmeanjan/d19c5dca071dc164bb9a273fc7185795#file-linkonmatic-sol) implementation, where I tried to keep things little shorter & contained.

Thanking you :wink:

**Comment by itzmeanjan** [comment]
[This](https://github.com/smartcontractkit/link-token-maticnetwork/blob/f17da49b40b6d71d89b0078bfe906b771922d7aa/migrations/02_deploy_link_token.js#L4) is wrong.

`ChildChainManagerProxy` [address](https://github.com/maticnetwork/static/blob/e9604415ee2510146cb3030c83d7dbebff6444ad/network/testnet/mumbai/index.json#L90) needs to be used. _( referenced link is for Matic Mumbai Network )_

**Comment by krebernisak** [comment]
Thanks, @itzmeanjan!

I've addressed some of your comments in :

- [Override LinkToken _onCreate hook](https://github.com/smartcontractkit/link-token-maticnetwork/commit/47e6566c9a0f67bd12be12023fc3155162b77672)
- [Improve deployment script to read static Matic Network config](https://github.com/smartcontractkit/link-token-maticnetwork/commit/80edeec35a2e454865e6ed232019aad3987effcc)

The [first check you mentioned](https://github.com/smartcontractkit/link-token-maticnetwork/blob/f17da49b40b6d71d89b0078bfe906b771922d7aa/flat/LinkTokenOnMatic.sol#L666), is part of the @openzeppelin ERC20 implementation, so I would say let's leave it like that even if it's not necessary. 

@itzmeanjan, could you please take another look?

**Comment by itzmeanjan** [comment]
Yes I checked updated implementation.

- [Looks better now](https://github.com/smartcontractkit/link-token-maticnetwork/commit/47e6566c9a0f67bd12be12023fc3155162b77672)
- [And it looks awesome now](https://github.com/smartcontractkit/link-token-maticnetwork/commit/80edeec35a2e454865e6ed232019aad3987effcc)

And other thing, as you mentioned, we can stay with that, no harm in keeping that address check.

Great work @krebernisak 👍

**Comment by krebernisak** [comment]
Thanks, @itzmeanjan! Closing this issue.
